# Generated by Django 4.1.3 on 2022-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rangers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ranger',
            name='color',
            field=models.CharField(choices=[('black', 'Black'), ('blue', 'Blue'), ('green', 'Green'), ('pink', 'Pink'), ('red', 'Red'), ('white', 'White'), ('yellow', 'Yellow')], max_length=16),
        ),
        migrations.AlterField(
            model_name='ranger',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
