RANGER_COLOR_BLACK = 'black'
RANGER_COLOR_BLUE = 'blue'
RANGER_COLOR_GREEN = 'green'
RANGER_COLOR_PINK = 'pink'
RANGER_COLOR_RED = 'red'
RANGER_COLOR_WHITE = 'white'
RANGER_COLOR_YELLOW = 'yellow'

RANGER_COLORS = (
    (RANGER_COLOR_BLACK, 'Black'),
    (RANGER_COLOR_BLUE, 'Blue'),
    (RANGER_COLOR_GREEN, 'Green'),
    (RANGER_COLOR_PINK, 'Pink'),
    (RANGER_COLOR_RED, 'Red'),
    (RANGER_COLOR_WHITE, 'White'),
    (RANGER_COLOR_YELLOW, 'Yellow'),
)
