# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zords', '0001_initial'),
        ('series', '0002_auto_20170223_1225'),
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('series__name',),
            },
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(choices=[(b'black', b'Black'), (b'blue', b'Blue'), (b'green', b'Green'), (b'pink', b'Pink'), (b'red', b'Red'), (b'white', b'White'), (b'yellow', b'Yellow')], max_length=16)),
                ('series', models.ManyToManyField(through='rangers.Appearance', to='series.Series')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='appearance',
            name='ranger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rangers.Ranger'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.Series'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='weapon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.Weapon'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='zord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zords.Zord'),
        ),
    ]
