# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.PositiveSmallIntegerField()),
                ('imdb_id', models.CharField(blank=True, default=None, max_length=9, null=True, unique=True)),
                ('trakt_id', models.IntegerField(blank=True, default=None, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='imdb_id',
            field=models.CharField(blank=True, default=None, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='series',
            name='trakt_id',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='series.Series'),
        ),
    ]
