# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 10:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Zord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[(b'carrierzord', b'Carrierzord'), (b'dinozord', b'Dinozord'), (b'ninjazord', b'Ninjazord'), (b'shogunzord', b'Shogunzord'), (b'thunderzord', b'Thunderzord')], max_length=32)),
                ('parts', models.ManyToManyField(blank=True, to='zords.Zord')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='mode',
            name='zord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='zords.Zord'),
        ),
    ]
