# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-05 12:58
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'allies',
            },
        ),
        migrations.CreateModel(
            name='Civilian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('nickname', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ranger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('color', models.CharField(
                    choices=[(b'black', b'Black'), (b'blue', b'Blue'), (b'green', b'Green'), (b'pink', b'Pink'),
                             (b'red', b'Red'), (b'white', b'White'), (b'yellow', b'Yellow')], max_length=16)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('gender',
                 models.CharField(blank=True, choices=[(b'female', b'Female'), (b'male', b'Male')], default=None,
                                  max_length=8, null=True)),
                ('type',
                 models.CharField(blank=True, choices=[(b'boss', b'Boss'), (b'minion', b'Minion')], default=None,
                                  max_length=8, null=True)),
                ('homeworld', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('series', models.ManyToManyField(blank=True, to='series.Series')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('type', models.CharField(
                    choices=[(b'axe', b'Axe'), (b'blaster', b'Blaster'), (b'bow', b'Bow'), (b'dagger', b'Dagger'),
                             (b'lance', b'Lance'), (b'sword', b'Sword')], max_length=16)),
                ('parts', models.ManyToManyField(blank=True, to='characters.Weapon')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
                ('type', models.CharField(
                    choices=[(b'carrierzord', b'Carrierzord'), (b'dinozord', b'Dinozord'), (b'ninjazord', b'Ninjazord'),
                             (b'shogunzord', b'Shogunzord'), (b'thunderzord', b'Thunderzord')], max_length=32)),
                ('parts', models.ManyToManyField(blank=True, to='characters.Zord')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZordMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField()),
                ('zord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes',
                                           to='characters.Zord')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='ranger',
            name='weapon',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       related_name='ranger', to='characters.Weapon'),
        ),
        migrations.AddField(
            model_name='ranger',
            name='zords',
            field=models.ManyToManyField(related_name='piloted_by', to='characters.Zord'),
        ),
    ]
