# Generated by Django 4.1.3 on 2022-12-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.CharField(choices=[('axe', 'Axe'), ('blaster', 'Blaster'), ('bow', 'Bow'), ('dagger', 'Dagger'), ('lance', 'Lance'), ('sword', 'Sword')], max_length=16),
        ),
    ]
