# Generated by Django 4.1.3 on 2022-12-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_alter_weapon_id_alter_weapon_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapon',
            old_name='type',
            new_name='category',
        ),
    ]
