# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0002_auto_20170223_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('gender', models.CharField(blank=True, choices=[(b'female', b'Female'), (b'male', b'Male')], default=None, max_length=8, null=True)),
                ('type', models.CharField(blank=True, choices=[(b'boss', b'Boss'), (b'minion', b'Minion')], default=None, max_length=32, null=True)),
                ('homeworld', models.CharField(blank=True, default=None, max_length=32, null=True)),
                ('series', models.ManyToManyField(blank=True, related_name='villains', to='series.Series')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
