GENDER_FEMALE = 'female'
GENDER_MALE = 'male'

GENDERS = (
    (GENDER_FEMALE, 'Female'),
    (GENDER_MALE, 'Male'),
)

VILLAIN_TYPE_ALCHEMIST = 'alchemist'
VILLAIN_TYPE_BOSS = 'boss'
VILLAIN_TYPE_GENERAL = 'general'
VILLAIN_TYPE_HENCHMAN = 'henchman'
VILLAIN_TYPE_MINION = 'minion'
VILLAIN_TYPE_SCIENTIST = 'scientist'

VILLAINS_TYPES = (
    (VILLAIN_TYPE_ALCHEMIST, 'Alchemist'),
    (VILLAIN_TYPE_BOSS, 'Boss'),
    (VILLAIN_TYPE_GENERAL, 'General'),
    (VILLAIN_TYPE_HENCHMAN, 'Henchman'),
    (VILLAIN_TYPE_MINION, 'Minion'),
    (VILLAIN_TYPE_SCIENTIST, 'Scientist'),
)
