# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('series', '0002_auto_20170223_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('series', models.ManyToManyField(blank=True, related_name='allies', to='series.Series')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'allies',
            },
        ),
    ]
