# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('type', models.CharField(choices=[(b'axe', b'Axe'), (b'blaster', b'Blaster'), (b'bow', b'Bow'), (b'dagger', b'Dagger'), (b'lance', b'Lance'), (b'sword', b'Sword')], max_length=16)),
                ('parts', models.ManyToManyField(blank=True, to='weapons.Weapon')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
